from .excel import SCHEMAS as EXCEL_SCHEMAS, REGISTRY as EXCEL_REGISTRY
from .pdf import SCHEMAS as PDF_SCHEMAS, REGISTRY as PDF_REGISTRY
from .docx import SCHEMAS as DOCX_SCHEMAS, REGISTRY as DOCX_REGISTRY
from .email import SCHEMAS as EMAIL_SCHEMAS, REGISTRY as EMAIL_REGISTRY

TOOLS_SCHEMA = EXCEL_SCHEMAS + PDF_SCHEMAS + DOCX_SCHEMAS + EMAIL_SCHEMAS
TOOL_REGISTRY = {**EXCEL_REGISTRY, **PDF_REGISTRY, **DOCX_REGISTRY, **EMAIL_REGISTRY}